version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mp-server-i
    container_name: mp-server-c
    volumes:
      - .:/usr/app/server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    # networks:
    #   - app-network
  
  mongodb:
    image: mongo:latest
    container_name: mongo-c
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1q2w3e4r
    # networks:
    #   - app-network
  
  client:
    build:
      context: ../Moy-povarenok-web-app-frontend
      dockerfile: Dockerfile
    image: mp-client-i
    container_name: mp-client-c
    volumes:
      - ../Moy-povarenok-web-app-frontend/:/usr/app/client
    depends_on:
      - server
    ports:
      - "3000:3000"
    # networks:
    #   - app-network
 
# networks:
#     app-network:
#         driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local